export let compMainTools = {
    numOfDuplicates: 0, 
    stopDuplicateTest: false, 
    newCompDeck: [], 
    mainBattleCard: null,
    singularityPoints: 0,
    cardSwitches: 0, 
    cardsToSwitch: [], 
    compChoiceOne: ['Attack', 'Defend', 'Switch'], 
    compChoiceTwo: ['Attack', 'Defend'], 
    isDefending: false, 
    supraMisses: [],
    fereMisses: [],
    bonumMisses: [], 
}