export let InitiatorCards = [
    {
        name: "Tobo The Fighter",
        cate: "supra",
        atk: 44,
        def: 12,
        esse: 100,
    },
    {
        name: "The One From System",
        cate: "supra",
        atk: 46,
        def: 10,
        esse: 100,
    }, 
    {
        name: "Spunky With The Funky Draco",
        cate: "supra",
        atk: 39,
        def: 11,
        esse: 100,
    },
    {
        name: "The Trendsetter Rotao",
        cate: "fere", 
        atk: 25,
        def: 18,
        esse: 100,
    },
    {
        name: "Allybelle",
        cate: "fere",
        atk: 27,
        def: 15,
        esse: 100, 
    },
    {
        name: "The Experiment",
        cate: "fere",
        atk: 24,
        def: 13,
        esse: 100, 
    },
    {
        name: "Dan The Prol",
        cate: "bonum",
        atk: 19,
        def: 22,
        esse: 100,
    },
    {
        name: "Mac The Rat",
        cate: "bonum",
        atk: 13,
        def: 28,
        esse: 100, 
    },
    {
        name: "A Karen",
        cate: "bonum",
        atk: 15,
        def: 26,
        esse: 100,
    },
    {
        name: "The office Worker Ken",
        cate: "bonum",
        atk: 16,
        def: 25,
        esse: 100,
    }
]